parameters:
  aw_sms.templating.loader.class: Accurateweb\SmsBundle\Template\Loader\DefaultTemplateLoader
  aw_sms.templating.engine.class: Accurateweb\SmsBundle\Template\Engine\SimpleTemplateEngine

services:
  aw_sms.template.loader:
    class: %aw_sms.templating.loader.class%

  aw_sms.template.engine:
    class: %aw_sms.templating.engine.class%

  aw_sms.template.factory:
    class: Accurateweb\SmsBundle\Sms\Factory\SmsFactory
    arguments:
      - @aw_sms.template.loader
      - @aw_sms.template.engine
